data=input("Enter text to write to the file:")
fo=open('output.txt','w')
fo.write(data)
print("data successfully written to output.txt")
fo.close()
fo1=open('output.txt','a')
d1=input("Enter additional text to append:")
fo1.write(d1)
print("Data successfully appended.")
fo1.close()
fo2=open('output.txt','r')
lines=fo2.readlines()
print(lines)
for line in lines:
    print(line,'\n')
fo2.close()    