data=input("Enter text to write to the file:")
fo=open('output.txt','w')
fo.write(data)
print("data successfully written to output.txt")
fo.close()
fo1=open('output.txt','a')
d1=input("Enter additional text to append:")
fo1.write(d1)
print("Data successfully appended.")
fo1.close()
fo=open('sample.txt','r')
lines=fo.read()
for line in lines.splitlines(True):
    print(line)
fo.close()    